language: go
go:
  - "1.x"
  - "1.10"
install:
  - go get -d -v ./...
jobs:
  include:
    - stage: docker-build
      script:
        - docker build -t cmattoon/aws-ssm:latest .
        
    - stage: docker-push
      script:
        - echo "$DOCKER_PASSWD" | docker login --username "$DOCKER_USER" --password-stdin
        - "docker push cmattoon/aws-ssm:tci-$TRAVIS_JOB_NUMBER"
stages:
  - name: install
  - name: docker-build
  - name: docker-push
    if: branch = master
