language: go
go:
  - "1.10"
before_install:
  - ./scripts/go_test.sh
jobs:
  include:
    - stage: docker-latest
      script:
        - docker build -t cmattoon/aws-ssm:dev .
        - docker tag cmattoon/aws-ssm:dev cmattoon/aws-ssm:latest
        - echo "$DOCKER_PASSWD" | docker login --username "$DOCKER_USER" --password-stdin
        - docker push cmattoon/aws-ssm:dev
        - docker push cmattoon/aws-ssm:latest
        
    - stage: docker-branch
      script:
        - docker build -t cmattoon/aws-ssm:$TRAVIS_BRANCH .
        - echo "$DOCKER_PASSWD" | docker login --username "$DOCKER_USER" --password-stdin
        - docker push cmattoon/aws-ssm:$TRAVIS_BRANCH

    - stage: docker-pr
      script:
        - docker build -t cmattoon/aws-ssm:PR-$TRAVIS_PULL_REQUEST .
        - echo "$DOCKER_PASSWD" | docker login --username "$DOCKER_USER" --password-stdin
        - docker push cmattoon/aws-ssm:PR-$TRAVIS_PULL_REQUEST
      
branches:
  only:
    - master
    - /^v.*$/

stages:
  - name: docker-latest
    if: branch = master AND type != pull_request
    
  - name: docker-branch
    if: branch != master AND type != pull_request
    
  - name: docker-pr
    if: type == pull_request

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
