language: go
go:
  - "1.x"
  - "1.10"
install:
  - go get -d -v ./...
jobs:
  include:
    - stage: docker-push-master
      script:
        - docker build -t cmattoon/aws-ssm:latest .
        - echo "$DOCKER_PASSWD" | docker login --username "$DOCKER_USER" --password-stdin
        - "docker push cmattoon/aws-ssm:latest"

    - stage: docker-tag
      script:
        - docker build -t cmattoon/aws-ssm:$TRAVIS_TAG .
        - echo "$DOCKER_PASSWD" | docker login --username "$DOCKER_USER" --password-stdin
        - "docker push cmattoon/aws-ssm:$TRAVIS_TAG"
branches:
  only:
    - master
    - /^v.*$/
stages:
  - name: install

  - name: docker-push-master
    if: branch = master

  - name: docker-tag
    if: branch != master
    
