version: '3'
services:

  aws_ssm:
    image: cmattoon/aws-ssm:latest
    build:
      context: .
    environment:
      AWS_ACCESS_KEY: ""
      AWS_SECRET_KEY: ""
      
    ports:
      - "9999:9999"
      
        
